const sample = [
  /*Ряд Тейлора */
  {
    name: "Ряд Тейлора",
    caption:
      "– представлення <b style='color: #ff2020'>функції</b> у вигляді нескінечної суми доданків.</br> Функція має вигляд:</br> <math-field read-only>f_{n+1}\\left(x\\right) = f\\left(x_0\\right)+\\frac{f^{\\prime}\\left(x_0\\right)}{1!}\\left(x-x_0\\right)+\\ldots\\ldots+\\frac{f^{\\left(n\\right)}\\left(x_0\\right)}{n!}\\left(x-x_0\\right)^{n}</math-field></br> Функція розкладається в ряд навколо заданої точки <math-field read-only class='nonfull'>x_0</math-field>. Збільшення аргументу по модулю потребує збільшення кількості доданків.",
    restricted: false,
    data: [
      {
        id: 1,
        data: [
          "Equal",
          ["f", "x"],
          //["Add", ["Multiply", 3, "x"], ["Square", "x"], 4],
          [
            "Equal",
            ["f", "x"],
            ["Sin", ["Add", ["Multiply", 4, "x"], ["Square", "x"]]],
          ],
          //["Sin", "x"],
        ],
        //text: "f^{}\\left(x\\right)=x^2+3x+4",
        text: "f\\left(x\\right)=\\sin\\left(x^2+4x\\right)",
        color: "459BE6",
        directiveColor: "E64545",
        directive: false,
        angle: false,
        visible: true,
        hidden: false,
      },
      {
        id: 2,
        data: [
          "RepeatFunction",
          [
            "Multiply",
            ["Divide", ["DerivativeFunction", "x_0", "k"], ["Factorial", "k"]],
            ["Power", ["Subtract", "x", "x_0"], "k"],
          ],
          0,
          "n",
        ],
        text: "",
        color: "ff2020",
        directiveColor: "20ff20",
        directive: false,
        angle: false,
        visible: true,
        hidden: true,
        points: [["x_0"]],
      },
    ],
    variable: [
      {
        id: 0,
        name: "n",
        range: [0, 10],
        value: 1,
        step: 1,
        hidden: false,
        restricted: true,
        anim: [1, 1, false],
      },
      {
        id: 1,
        name: "x_0",
        range: [-10, 10],
        value: 0,
        step: 0.1,
        hidden: false,
        restricted: false,
      },
    ],
  },
  /*Січна та дотична */
  {
    name: "Січна та дотична",
    caption:
      "Побудуємо <b style='color: #20ff20'>дотичну</b> в точці <math-field read-only class='nonfull'>x_0</math-field> за формулою: </br> <math-field read-only>f\\left(x\\right)= f\\left(x_0\\right)+f^{\\prime}\\left(x_0\\right)\\left(x-x_0\\right)</math-field></br> Будуємо <b style='color: #ff2020'>січну</b> за точками <math-field read-only class='nonfull'>x_0</math-field> та <math-field read-only class='nonfull'>x_1</math-field> за формулою: </br> <math-field read-only>f\\left(x\\right) = \\frac{f\\left(x_1\\right)-f\\left(x_0\\right)}{x_1-x_0}\\cdot\\left(x-x_0\\right)+f\\left(x_0\\right)</math-field></br>При наближені <math-field read-only class='nonfull'>x_1</math-field> до <math-field read-only class='nonfull'>x_0</math-field> січна буде наближатися до дотичної. Таким чином ми отримуємо граничний перехід від січної до дотичної.",
    restricted: false,
    data: [
      {
        id: 1,
        data: [
          "Equal",
          ["f", "x"],
          ["Multiply", ["Rational", 1, 5], ["Square", "x"]],
        ],
        text: "f\\left(x\\right)=\\frac15x^2",
        color: "459BE6",
        directiveColor: "E64545",
        directive: false,
        angle: false,
        visible: true,
        hidden: false,
      },
      {
        id: 2,
        data: [
          "Add",
          [
            "Multiply",
            ["DerivativeFunction", "x_0", 1],
            ["Subtract", "x", "x_0"],
          ],
          ["f", "x_0"],
        ],
        text: "",
        color: "20ff20",
        directiveColor: "10bb10",
        directive: false,
        angle: true,
        visible: true,
        hidden: true,
        points: [["x_0"]],
      },
      {
        id: 3,
        data: [
          // (f(x_1)- f(x_0))/ (x_1 - x_0)* (x-x_0)+ f(x_0)
          "Add",
          [
            "Multiply",
            [
              "Divide",
              ["Subtract", ["f", "x_1"], ["f", "x_0"]],
              ["Subtract", "x_1", "x_0"],
            ],
            ["Subtract", "x", "x_0"],
          ],
          ["f", "x_0"],
        ],
        text: "",
        color: "ff2020",
        directiveColor: "bb1010",
        directive: false,
        angle: true,
        visible: true,
        hidden: true,
        points: [["x_0"], ["x_1"]],
      },
    ],
    variable: [
      {
        id: 1,
        name: "x_0",
        range: [-10, 10],
        value: 1,
        step: 0.1,
        hidden: false,
        restricted: false,
      },
      {
        id: 0,
        name: "x_1",
        range: [-10, 10],
        value: 4,
        step: 0.1,
        hidden: false,
        restricted: false,
        anim: [-0.1, 0.01, false],
      },
    ],
  },
  /*Тангенсний трикутник */
  {
    name: "Slope трикутник",
    caption: [
      "Побудуємо <b style='color: #20ff20'>дотичну</b> в точці <math-field read-only class='nonfull'>x_0</math-field> за формулою: </br> <math-field read-only>f\\left(x\\right)= f\\left(x_0\\right)+f^{\\prime}\\left(x_0\\right)\\left(x-x_0\\right)</math-field></br> Також будуємо графік <b style='color: #ff2020'>похідної</b> від функції. </br> Будуємо 1-й відрізок, що паралельний лінії вісі абсцис  <math-field read-only class='nonfull'>xє\\left\\lbrack x_0-0.5;x_0+0.5\\right\\rbrack</math-field>(відрізок довжиною 1).</br>",
      "Добудовуємо прямокутний трикутник. </br>Так як кут між відрізком до дотичної буде дорівнювати нахилу дотичної до додатного напряму осі абцис(паралельніcть прямих), то довжина іншого відрізку буде дорівнювати модулю тангенсу кута <b>(для доведення будемо враховувати знак тангенсу)</b></br></br>У висновку значення похідної в точці <math-field read-only class='nonfull'>x_0</math-field> дорівнює значенню тангенсу кута нахилу дотичної до додатного напрямку осі абцис. Це доведення геометричного означення похідної.",
    ],
    restricted: false,
    data: [
      {
        id: 1,
        data: [
          "Equal",
          ["f", "x"],
          ["Add", ["Multiply", "Half", ["Square", "x"]], "x", -4],
          //["Square", "x"],
        ],
        text: "f\\left(x\\right)=\\frac12x^2+x-4",
        //text: "f\\left(x\\right)=x^2",
        color: "459BE6",
        directiveColor: "E64545",
        directive: false,
        angle: false,
        visible: true,
        hidden: false,
      },
      {
        id: 2,
        data: [
          "Equal",
          ["g", "x"],
          //["Add", ["Multiply", "Half", ["Square", "x"]], "x", -4],
          [
            "Add",
            [
              "Multiply",
              ["DerivativeFunction", "x_0", 1],
              ["Subtract", "x", "x_0"],
            ],
            ["f", "x_0"],
          ],
        ],
        text: "",
        color: "20ff20",
        directiveColor: "10bb10",
        directive: false,
        angle: false,
        visible: true,
        hidden: true,
        triangle: ["x_0", 1],
        points: [["x_0"]],
      },
      {
        id: 3,
        data: ["DerivativeFunction", "x", 1],
        text: "",
        color: "ff2020",
        directiveColor: "bb1010",
        directive: false,
        angle: false,
        visible: true,
        hidden: true,
        oy: "x_0",
      },
    ],
    variable: [
      {
        id: 0,
        name: "x_0",
        range: [-10, 10],
        value: 1,
        step: 0.1,
        hidden: false,
        restricted: false,
      },
    ],
  },
];

export default sample;
